In [1]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

11501568/11490434 [==============================] - 1s 0us/step
Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2983 - accuracy: 0.9126
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1451 - accuracy: 0.9573
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1077 - accuracy: 0.9678
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0893 - accuracy: 0.9722
Epoch 5/5
313/313 [==============================] - 0s 965us/step - loss: 0.0795 - accuracy: 0.9730


[0.07947272062301636, 0.9729999899864197]

In [9]:
print(tf.__version__)
import numpy as np
print("\n\n")
print('==========')
t1 = tf.Variable([1,2, 3]) # 파라미터 역할
t2= tf.constant([1,2, 3])  # 데이터 셋에 들어가는거
print(t1)
print(t2)
print("\n")
print('==========')

print("\n")
print(type(t1))
print(type(t2))

2.8.0



<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)




<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [16]:
test_list = [1, 2, 3]
test_np = np.array([1, 2, 3])


print(type(test_list))
print(type(test_np))

# tf-constant
t1 = tf.constant(test_list)
t2 = tf.constant(test_np)

print(t1)
print(t2)

print(type(t1)) # EagerTensor 
print(type(t2))

<class 'list'>
<class 'numpy.ndarray'>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [18]:
test_list = [1, 2, 3]
test_np = np.array([1, 2, 3])

# tf-Variable
t1 = tf.Variable(test_list)
t2 = tf.Variable(test_np)




print(t1)
print(t2)

print(type(t1)) # EagerTensor 
print(type(t2))



<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [20]:

# constant => variable로 변경가능하지만
# variable에서 constant로는 변경이 불가능하다.



test_list = [1, 2, 3]
test_np = np.array([1, 2, 3])

t1 = tf.constant(test_list)
t2 = tf.Variable(test_np)


t4 = tf.Variable(t1)
print(t4)
print(type(t4))


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
